#pragma once
#include <string>
#include <map>
#include <vector>
#include <set>

namespace iknow {
	namespace csvdata {
		class CSV_DataGenerator; // forward to avoid circular include

		typedef std::map<std::string, int> newLabelsIndex_type; // mapping new labels to index in newLabels_type
		typedef std::vector<std::pair<std::string, std::string> > newLabels_type; // new labelName and phase store

		typedef std::set<std::string> SPhases_type; // collector for auto-generated label phases
		typedef std::pair<iKnow_KB_Label, SPhases_type> Label_Phases; // a label linked to it's auto-generated phases
		typedef std::vector<Label_Phases>	AutoGeneratedLabels_type; // the collection of auto-generated labels

		class iKnow_KB_Rule
		{
		public:
			// ClassMethod ImportFromStream(stream As %CharacterStream, kb As Knowledgebase)
			static bool ImportFromCSV(std::string rule_csv, CSV_DataGenerator& kb);

			std::vector<std::string> TransformRulePattern(std::string& csv_rule_input, std::string& csv_phase, CSV_DataGenerator& kb, newLabels_type &newLabels, newLabelsIndex_type &newLabelsIndex, AutoGeneratedLabels_type&);
			void ProcessRuleOutputPattern(std::string& pattern, std::string& phase, CSV_DataGenerator&, AutoGeneratedLabels_type&);
			std::string csv_id; // identification number in csv-file

			std::vector<std::string> InputPattern, OutputPattern;
			int Precedence;
			std::string Phase;

			iKnow_KB_Rule() {}
			~iKnow_KB_Rule() {}
		};
	}
}